#!/bin/bash

set -eu

book_name=$1
if [ ! -n "$OUTDIR" ] || [ ! -n "$book_name" ]; then
  echo 'You must set $OUTDIR and pass the books filename as the only argument'
  exit 1
fi

cd $(dirname $0)

echo "Convert epub file to mobi"
ebook-convert $book_name.epub  $OUTDIR/$book_name.mobi > /dev/null

if [ -f "$book_name.mobi" ]; then
    echo "Created  $OUTDIR/$book_name.mobi"
fi
