#!/bin/bash

set -eu

while getopts i:o: flag
do
    case "${flag}" in
        i) input=${OPTARG};;
        o) output=${OPTARG};;
    esac
done

cd $(dirname $0)

ebook-convert $input  $output \
	      --embed-all-fonts \
	      --remove-first-image > /dev/null

